[build]
builder = "nixpacks"

[[services]]
name = "backend"
source = "langgraph-evol-instruct-mvp/backend"

[services.build]
buildCommand = "pip install -r requirements.txt"

[services.deploy]
startCommand = "uvicorn api_server:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"

[[services]]
name = "frontend" 
source = "frontend"

[services.build]
buildCommand = "npm install && npm run build"

[services.deploy]
startCommand = "npx serve -s dist/langgraph-evol-instruct-frontend -l $PORT"
restartPolicyType = "on_failure" 